export const VOLUNTEER_ACTIONS = {
  FETCH_VOLUNTEER_DATA: 'FETCH_VOLUNTEER_DATA',
  FETCH_ALL_VOLUNTEERS: 'FETCH_ALL_VOLUNTEERS',
  SET_ALL_VOLUNTEERS: 'SET_ALL_VOLUNTEERS',
  FETCH_EVENT_VOLUNTEERS: 'FETCH_EVENT_VOLUNTEERS',
  SET_EVENT_VOLUNTEER: 'SET_EVENT_VOLUNTEER',
  VOLUNTEER_DATA_FETCH_FAILED: 'VOLUNTEER_DATA_FETCH_FAILED',
  PUT_VOLUNTEER_DATA: 'PUT_VOLUNTEER_DATA',
  POST_VOLUNTEER: 'POST_VOLUNTEER',
  DELETE_VOLUNTEER: 'DELETE_VOLUNTEER'
}

// export const triggerUpdateEvent = (volunteerId, newEventData) => ({
//   type: VOLUNTEER_ACTIONS.PUT_VOLUNTEER_DATA,
//   payload: [volunteerId, newEventData]
// })
// export const triggerDeleteEvent = (volunteerId) => ({
//   type: VOLUNTEER_ACTIONS.DELETE_VOLUNTEER,
//   payload: volunteerId
// })